tasks:
  - name: servidor
    init: npm install --prefix servidor
    command: npm start --prefix servidor
  - name: eslint
    init: npm install eslint --save-dev

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dbaeumer.vscode-eslint